### ISSUE TITLE
2-3 Dicom Image Viewer 개선

### ISSUE THREAD

**Issue by shingagyoung** [shingagyoung/task#10]
- #1 에 대한 하위이슈 입니다.

### Dicom Image Viewer에 추가적인 기능 도입하기
  - [x] WWL 기능 추가 (Window width, Window level)
  - [x] sagittal, coronal view 추가

**Comment by shingagyoung** [comment]
#### 현재 진행 상황
1. **WWL 기능**
- header에 나온 wwl으로는 렌더링 되도록 반영하였습니다. 
- 3d slicer 처럼 wwl 값이 변하는 대로 이미지에 반영 되도록 하는 작업 진행 중입니다.

2. **sagittal, coronal view**
- sagittal 완료.
- coronal은 데이터를 axial과 동일한 순서로 읽었더니 상하가 뒤집힌 결과로 나와서 수정 중에 있습니다. 

<img src="https://github.com/shingagyoung/task/assets/168696469/59072a3f-0ccb-443d-9922-8d08b5f9d2f2" width = 450 height = 650> </img>

<img src="https://github.com/shingagyoung/task/assets/168696469/7909cc12-bf03-4d93-a1ca-a10be32959df" width = 450 height = 650> </img>

**Comment by shingagyoung** [comment]
** 현재 진행 상황
- 완료
    - Coronal view orientation 변경 완료. (상하가 뒤집어져서 나왔었음.)
<img src="https://github.com/shingagyoung/task/assets/168696469/531b527d-1622-47ec-8100-99e7e0456aff" width = 250 height = 450> </img>


   - Series cell 화면에 이미지 보여줄 때 기존에는 모든 plane 이미지를 한 번에 생성하고 있었습니다. 그러다 보니 시간 소요가 너무 심해, 선택된 plane의 이미지만 생성하는 방식으로 변경하였습니다.
   - 개별 이미지 생성 작업 중 screen freeze가 있어서 이미지 생성 연산을 background queue로 보내는 방식 적용해서 freeze 해결하였습니다.

- 진행 중
   - wwl 값 변경에 따라 이미지에 반영하는 작업 진행 중입니다.

**Comment by shingagyoung** [comment]
#### 현재 진행 상황

- 완료
  - wwl 값 변경에 따라 이미지에 반영하는 작업 완료.
    - ww, wl 가 바뀌면 min, max 값을 계산하여 clamping 한 뒤에 grayscale로 normalize하고 있습니다.
    - slicer처럼 부드럽게 변경이 되지는 않고, APPLY 버튼을 눌렀을 때 데이터에 연산을 수행하여 이미지를 생성해내고 있습니다. 

| img1 | img2 | img3 |
| --- | --- | --- |
| <img src="https://github.com/shingagyoung/task/assets/168696469/7a8a1499-2ca4-4987-a215-223871d89038" width = 250 height = 450> </img> | <img src="https://github.com/shingagyoung/task/assets/168696469/8404b0ac-ec4c-4871-bffc-c230e0eb1196" width = 250 height = 450> </img>| <img src="https://github.com/shingagyoung/task/assets/168696469/ecf6adb7-d799-429d-8b61-13e45702f4d7" width = 250 height = 450> </img> |

- 진행 중
  - 현재 이전 이슈에 대한 PR 지속적으로 진행 중에 있습니다. 현재 이슈 PR 진행 전까지 버그 등 오류가 있는 지 확인해보고, 있다면 수정하도록 하겠습니다.

**Comment by shingagyoung** [comment]
**수정사항**
nrrd 이미지를 보고 나서 셀을 접은 후 다시 펼쳤을 때, 가장 마지막에 보고 있던 plane이 나타나지 않고 axial 이미지가 보이는 문제가 있었습니다. 앱 사용자라면 가장 최근에 보았던 이미지와 wwl이 다시 나오기를 기대할 것 같아서 해당 부분 수정하였습니다.

**Comment by hyunheeskia** [comment]
![image](https://github.com/shingagyoung/task/assets/134245511/68bdbfe4-1aea-4401-b38b-e8c832922060)

apply 버튼을 누르면 항상 0번째 slice 로 이동합니다.
