### ISSUE TITLE
2-2 Dicom Image Viewer 구현

### ISSUE THREAD

**Issue by shingagyoung** [shingagyoung/task#8]
- #1 에 대한 하위이슈 입니다.

### DicomSeries의 volume file 읽고 화면에 띄우기
  - [x] volume (CT .nrrd) file 을 읽어 화면에 image 띄우기 (axial 만)
  - [x] UI 추가하여 image index 를 바꿔가며 볼 수 있도록 구현

**Comment by shingagyoung** [comment]
#### 현재 작업 진행 사항
- image index별 열람 가능 하나, 이미지의 흑백 구분이 선명하게 나오지 않아서 해당 부분 작업 중에 있습니다. 
<img src="https://github.com/shingagyoung/task/assets/168696469/c4b9400a-291a-406b-89d7-9695185c0e44" width = 300 height = 550> </img>

**Comment by shingagyoung** [comment]
- 이미지 byte array에서 짝수 index마다 나오는 252를 0으로 치환한 이후의 모습. 관찰하고자 하는 대상에도 영향을 주어 좋은 방법은 아닌 것 같습니다..
<img src="https://github.com/shingagyoung/task/assets/168696469/bc3ff55e-7340-4ea5-9b76-501e8fb8cbd7" width = 300 height = 550> </img>

**Comment by shingagyoung** [comment]
- nrrd header에 나온 type 정보 (short)를 활용하여 처리 방식을 변경하였습니다. 
```
NRRD0004
# Complete NRRD file format specification at:
# http://teem.sourceforge.net/nrrd/format.html
type: short
dimension: 3
``` 
- UInt8으로 처리하던 것을 UInt16으로 처리하였더니, 화질이 제대로 나오는 것 같습니다. 
- 이미지 사이즈 및 코드 부분 조금 더 수정해서 마무리 할 수 있도록 하겠습니다.
 

<img src="https://github.com/shingagyoung/task/assets/168696469/679e6775-b9b6-46fd-96a0-574bf2e755e1" width = 400 height = 650> </img>

**Comment by alkee-skia** [comment]
> 이미지 byte array에서 짝수 index마다 나오는 252를 0으로 치환한 이후의 모습. 관찰하고자 하는 대상에도 영향을 주어 좋은 방법은 아닌 것 같습니다..

이렇게 치환해 정상적인것처럼(?) 보여졌다면, (올바른 방식이 아니라 되는 것 처럼 보이는 방식?) 오히려 문제가 더 심각해 질 수 있습니다. 시간히 지날 수록 뭍혀있던 문제들은 크게 증폭되거든요..

**Comment by shingagyoung** [comment]
> > 이미지 byte array에서 짝수 index마다 나오는 252를 0으로 치환한 이후의 모습. 관찰하고자 하는 대상에도 영향을 주어 좋은 방법은 아닌 것 같습니다..
> 
> 이렇게 치환해 정상적인것처럼(?) 보여졌다면, (올바른 방식이 아니라 되는 것 처럼 보이는 방식?) 오히려 문제가 더 심각해 질 수 있습니다. 시간히 지날 수록 뭍혀있던 문제들은 크게 증폭되거든요..

네 맞습니다. 정확하지 못한 임의 방식을 실제 코드에 반영하는 일은 없도록 하겠습니다~

**Comment by shingagyoung** [comment]
#### 현재 진행 상황
- 이미지 데이터 처리 관련 사항 마무리.
- TableView cell 선택하여 expand할 때마다 api call 발생하고 있는데, 매번 call을 하는 것이 비효율적이다보니 해당 부분에 대해 caching을 적용해보겠습니다.

**Comment by shingagyoung** [comment]
#### `서버 API call`, `Nrrd load`, `Nrrd to UIImage` 변환 부분에 caching 적용하였습니다.
- `Nrrd load`, `UIImage 변환` 부분에서 시간이 많이 소요되는데, 캐시 사용 이후 아래와 같이 소요 시간이 축소되었습니다. 
- 현재 서버에서 불러오는 가장 이미지 수가 많은 nrrd 파일 기준
   -  nrrd load: 약 6초 -> 약 2초
   - 이미지 변환: 약 7초 -> 약 0.001초
   
![스크린샷 2024-05-17 오후 3 00 06](https://github.com/shingagyoung/task/assets/168696469/a19bc7ba-cebe-454a-a343-369cb168006f)
<적용 전>

![스크린샷 2024-05-17 오후 3 08 55](https://github.com/shingagyoung/task/assets/168696469/3b7fe1e5-ab18-4f3c-857b-63fed91c9f76)
<적용 후>

*Nrrd load 부분 캐싱 적용을 위해 NrrdRaw 파일에 캐싱 관련 로직을 추가하였습니다. 혹시 문제가 된다면 별도의 class를 구성하여 해당 부분 빼내도록 하겠습니다.
